import { test, expect, Page } from '@playwright/test';
import { Constants } from '../../helpers/constants';
import { AddTruckPage } from '../../page/truck/addTruck.page';
import { TruckPage } from '../../page/truck/truck.page';
import { get17RandomNumbers, get6RandomNumber } from '../../helpers/dateUtilis';

test.use({ storageState: 'auth.json' });

let page: Page;

test.beforeEach(async ({ page }) => {
    const add = new AddTruckPage(page);
    const truck = new TruckPage(page);
    await page.goto(Constants.truckUrl);
    await truck.truckColumn.first().waitFor({ state: 'visible', timeout: 10000 });
    await truck.addButton.click();
    await add.phoneField.waitFor({ state: 'visible', timeout: 10000 });
});

test('Korisnik moze da doda i obrise truck', async ({ page }) => {
    const add = new AddTruckPage(page);
    const truck = new TruckPage(page);
    page.on('dialog', async (dialog) => {
        await dialog.accept();
    });
    const truckNumber = get6RandomNumber().join('');
    await add.enterTruckNumber(add.truckNumberField, truckNumber);
    await add.selectDriver(add.driverField, Constants.driverPlaywright, add.driverOption);
    await add.enterInfo(add.infoField, Constants.noteFirst);
    await add.enterPhone(add.phoneField, Constants.phoneNumberOfUserApp);
    await add.selectDivision(add.divisionMenu, add.testCompanyDivisionOption);
    await add.selectMake(add.makeMenu, add.volvoMakeOption);
    await add.selectModel(add.modelMenu, add.VNL760ModleOption);
    await add.enterColor(add.truckColorField, Constants.truckColor);
    await add.selectYear(add.yearMenu, add.year2002);
    const vin = get17RandomNumbers().join('');
    await add.enterVinNumber(add.vinNumberField, vin);
    await add.enterPlate(add.plateField, Constants.plateNumber);
    await add.selectTruckEngine(add.truckEngineMenu, add.cumminsTruckEngine);
    await add.selectTransmission(add.transmissionMenu, add.automaticTransmissionOption);
    await add.enterMileage(add.truckMileageMenu, Constants.millage);
    await add.check(add.rentedRadioButton);
    await add.check(add.brokenTruckRadioButton);
    await add.check(add.totalDemage);
    await add.addButtonInModal.click();
    await add.dialogBox.waitFor({ state: 'detached', timeout: 10000 });
    await truck.enterTruckName(truck.searchInput, truckNumber);
    await page.waitForLoadState('networkidle');
    const truckCell = page.locator(`tr:nth-child(1) td:nth-child(2):has-text("${truckNumber}")`);
    await expect(truckCell).toBeVisible({ timeout: 10000 });
    await expect(truck.truckColumn).toContainText(truckNumber);
    await expect(truck.driverColumn).toContainText(Constants.driverPlaywright);
    await expect(truck.infoColumn).toContainText(Constants.noteFirst);
    await expect(truck.phoneColumn).toContainText(Constants.phoneNumberOfUserApp);
    await expect(truck.divisionColumn).toContainText(Constants.testCompany);
    await expect(truck.makeColumn).toContainText(Constants.makeVolvo);
    await expect(truck.modelColumn).toContainText(Constants.model);
    await expect(truck.colorColumn).toContainText(Constants.truckColor);
    await expect(truck.yearColumn).toContainText(Constants.year2022);
    await expect(truck.vinColumn).toContainText(vin);
    await expect(truck.plateColumn).toContainText(Constants.plateNumber);
    await expect(truck.engineColumn).toContainText(Constants.cumminsTruckEngine);
    await expect(truck.transsmissionColumn).toContainText(Constants.automaticTransmission);
    await expect(truck.mileageColumn).toContainText(Constants.millage);
    await expect(truck.isBrokenColumn).toHaveClass(/mdi-check/);
    await expect(truck.isDemagedColumn).toHaveClass(/mdi-check/);
    await expect(truck.totalDemageTitle).toBeVisible();
    const bgColor = await truck.totalDemageTitle.evaluate(el => window.getComputedStyle(el).backgroundColor);
    await expect(bgColor).toBe(Constants.totalDemageColor);
    await truck.pencilIcon.click();
    await add.phoneField.waitFor({ state: 'visible', timeout: 10000 });
    await add.deleteButton.click();
    await expect(truck.snackMessage).toContainText(truckNumber + ' successfully deleted');
});

test('Korisnik moze da doda truck - third party', async ({ page }) => {
    const add = new AddTruckPage(page);
    const truck = new TruckPage(page);
    const truckNumber = get6RandomNumber().join('');
    await add.check(add.thirdPartyRadioButton);
    await add.enterTruckNumber(add.truckNumberField, truckNumber);
    await add.selectThirdParty(add.thirdPartyMenu, add.thirtPartyOption);
    await add.enterInfo(add.infoField, Constants.noteFirst);
    await add.enterPhone(add.phoneField, Constants.phoneNumberOfUserApp);
    await add.selectDivision(add.divisionMenu, add.testCompanyDivisionOption);
    await add.selectMake(add.makeMenu, add.volvoMakeOption);
    await add.selectModel(add.modelMenu, add.VNL760ModleOption);
    await add.enterColor(add.truckColorField, Constants.truckColor);
    await add.selectYear(add.yearMenu, add.year2002);
    const vin = get17RandomNumbers().join('');
    await add.enterVinNumber(add.vinNumberField, vin);
    await add.enterPlate(add.plateField, Constants.plateNumber);
    await add.selectTruckEngine(add.truckEngineMenu, add.cumminsTruckEngine);
    await add.selectTransmission(add.transmissionMenu, add.automaticTransmissionOption);
    await add.enterMileage(add.truckMileageMenu, Constants.millage);
    await add.check(add.rentedRadioButton);
    await add.check(add.brokenTruckRadioButton);
    await add.check(add.totalDemage);
    await add.addButtonInModal.click();
    await add.dialogBox.waitFor({ state: 'detached', timeout: 10000 });
    await truck.enterTruckName(truck.searchInput, truckNumber);
    await page.waitForLoadState('networkidle');
    const truckCell = page.locator(`tr:nth-child(1) td:nth-child(2):has-text("${truckNumber}")`);
    await expect(truckCell).toBeVisible({ timeout: 10000 });
    await expect(truck.truckColumn).toContainText(truckNumber);
    await expect(truck.driverColumn).toContainText(Constants.owner);
    await expect(truck.infoColumn).toContainText(Constants.noteFirst);
    await expect(truck.phoneColumn).toContainText(Constants.phoneNumberOfUserApp);
    await expect(truck.divisionColumn).toContainText(Constants.testCompany);
    await expect(truck.makeColumn).toContainText(Constants.makeVolvo);
    await expect(truck.modelColumn).toContainText(Constants.model);
    await expect(truck.colorColumn).toContainText(Constants.truckColor);
    await expect(truck.yearColumn).toContainText(Constants.year2022);
    await expect(truck.vinColumn).toContainText(vin);
    await expect(truck.plateColumn).toContainText(Constants.plateNumber);
    await expect(truck.engineColumn).toContainText(Constants.cumminsTruckEngine);
    await expect(truck.transsmissionColumn).toContainText(Constants.automaticTransmission);
    await expect(truck.mileageColumn).toContainText(Constants.millage);
    await expect(truck.isBrokenColumn).toHaveClass(/mdi-check/);
    await expect(truck.isDemagedColumn).toHaveClass(/mdi-check/);
    await expect(truck.totalDemageTitle).toBeVisible();
    const bgColor = await truck.totalDemageTitle.evaluate(el => window.getComputedStyle(el).backgroundColor);
    await expect(bgColor).toBe(Constants.totalDemageColor);
});

test('Korisnik moze da prebaci truck u inactive', async ({ page }) => {
    const add = new AddTruckPage(page);
    const truck = new TruckPage(page);
    page.on('dialog', async (dialog) => {
        await dialog.accept();
    });
    await add.cancelButton.click();
    await add.dialogBox.waitFor({ state: 'detached', timeout: 5000 });
    const truckNumber = await truck.truckColumn.first().allInnerTexts();
    await truck.pencilIcon.first().click();
    await add.phoneField.waitFor({ state: 'visible', timeout: 10000 });
    await add.inactiveButton.click();
    await expect(truck.snackMessage).toContainText(truckNumber + ' successfully released');
});
