# name: Run Playwright Tests

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   tests:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: npm ci

#       - name: Install Playwright Browsers
#         run: npx playwright install chromium

#       - name: Run Playwright tests
#         run: npx playwright test

name: Run Changed Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # važno da imamo ceo Git diff

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Detect changed test folders
        id: detect
        run: |
          echo "📂 Git diff:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          
          TEST_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '^tests/' \
            | awk -F/ '{print $1"/"$2}' \
            | sort -u | xargs)
          
          echo "✅ Detected changed test directories: $TEST_DIRS"
          echo "TEST_DIRS=$TEST_DIRS" >> $GITHUB_ENV

      - name: Run Playwright tests for changed folders
        if: env.TEST_DIRS != ''
        run: |
          echo "🚀 Running tests in: $TEST_DIRS"
          npx playwright test $TEST_DIRS


